-- Saved from the current live tuning panel.
return {
 showSpeedometer=true,
 values={AirPoseThreshold=30,AirPoseStartLean=30,AirPoseMaxLean=60,AirPoseFullSpeed=150,AirAcceleration=160,AirDrag=0.5,AirSpeed=40,AnchorRange=750,CoastDrag=1.5,ForceFarClamp=150,ForceNearClamp=5,Gravity=60,GroundAcceleration=70,GroundSpeed=40,JumpStrength=8,PullAcceleration=1000,PullFalloff=0.1,PullSpeed=160,PushAcceleration=1000,PushFalloff=0.1,PushSpeed=160,SlideBraking=80,SlideLeftSteering=30,SlideRightSteering=30,SlideSMinSpeed=30,SlideWAcceleration=25,SlideWTopSpeed=200,StopSpeed=30},
 ranges={AirPoseThreshold={0,300},AirPoseStartLean={0,80},AirPoseMaxLean={0,80},AirPoseFullSpeed={0,500},AirAcceleration={0,1000},AirDrag={0,8},AirSpeed={0,200},AnchorRange={0,1000},CoastDrag={0,8},ForceFarClamp={0.1,500},ForceNearClamp={0.1,50},Gravity={0,400},GroundAcceleration={0,500},GroundSpeed={0,100},JumpStrength={0,50},PullAcceleration={50,2000},PullFalloff={0,5},PullSpeed={20,400},PushAcceleration={50,2000},PushFalloff={0,5},PushSpeed={20,400},SlideBraking={0,1000},SlideLeftSteering={0,360},SlideRightSteering={0,360},SlideSMinSpeed={0,200},SlideWAcceleration={0,200},SlideWTopSpeed={0,500},StopSpeed={0,30}},
}
